const $ = s => document.querySelector(s); let ws, next=0, tab='agents', pending=new Map(), token='', granted=[]
const routes={agents:'agent.list',workflows:'workflow.list',cost:'usage.cost'}
function setConnection(ok,text){$('#connection').className=ok?'online':'offline';$('#connection').textContent=text}
function call(method,params={}){return new Promise((resolve,reject)=>{if(!ws||ws.readyState!==1)return reject(new Error('Gateway is disconnected'));const id=++next;pending.set(id,{resolve,reject});ws.send(JSON.stringify({jsonrpc:'2.0',id,method,params}));setTimeout(()=>{if(pending.delete(id))reject(new Error(`${method} timed out`))},15000)})}
function connect(){ws?.close(); const url=$('#url').value.trim(); token=$('#token').value; if(!/^wss:\/\//.test(url)&&!/^ws:\/\/(127(?:\.\d+){3}|\[::1\])(?::\d+)?\//.test(url)){return setConnection(false,'Refused: remote gateways require WSS')} ws=new WebSocket(url); ws.onopen=async()=>{try{const hello=await call('gateway.hello',{protocol_version:1,client_id:'carina-web',role:'observer',scopes:['read'],token});granted=hello.scopes||[];setConnection(true,`Connected (${granted.join(', ')})`);render()}catch(e){setConnection(false,e.message);ws.close()}};ws.onmessage=e=>{const m=JSON.parse(e.data);const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)}};ws.onclose=()=>{setConnection(false,'Disconnected');for(const p of pending.values())p.reject(new Error('Gateway disconnected'));pending.clear()};ws.onerror=()=>setConnection(false,'Connection failed')}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
async function render(){const out=$('#content');out.innerHTML='<p class="muted">Loading…</p>';try{const data=await call(routes[tab]);const rows=Array.isArray(data)?data:(data.agents||data.providers||[]);if(!rows.length){out.innerHTML='<p class="muted">No records.</p>';return}out.innerHTML=rows.map(x=>`<div class="row ${x.needs_input?'needs':''}"><strong>${esc(x.title||x.name||x.workflow||x.provider||x.session_id||x.id)}</strong><span>${esc(x.needs_input?'Needs input':x.status||x.model||'')}</span><span>${esc(x.cost_usd!=null?'$'+Number(x.cost_usd).toFixed(4):x.progress!=null?Math.round(x.progress*100)+'%':x.workspace_root||'')}</span>${x.task_id&&$('#writes').checked?`<button data-steer="${esc(x.task_id)}">Steer</button>`:''}</div>`).join('')}catch(e){out.innerHTML=`<p class="error">${esc(e.message)}. Check daemon, Gateway URL, token expiry, and read scope.</p>`}}
async function confirmed(method,params){if(!$('#writes').checked)throw new Error('Write controls are disabled');$('#operation').textContent=JSON.stringify({method,params},null,2);$('#confirm').showModal();if(await new Promise(r=>{const d=$('#confirm');d.addEventListener('close',()=>r(d.returnValue==='default'),{once:true})}))return call(method,params)}
$('#settings').onclick=()=>$('#connect').showModal();$('#connectNow').onclick=connect;$('#refresh').onclick=render;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');b.classList.add('active');tab=b.dataset.tab;render()});$('#content').onclick=async e=>{const id=e.target.dataset?.steer;if(!id)return;const message=prompt('Steering message');if(message)try{await confirmed('task.steer',{task_id:id,message});render()}catch(err){alert(err.message)}};$('#writes').onchange=render;$('#connect').showModal()
export { esc }
