const $=s=>document.querySelector(s);let ws,next=0,tab='agents',pending=new Map(),granted=[],methods=new Map(),reconnectTimer,backoff=250,intentional=false,streams=new Map(),cursors=new Map(),snapshot,stale=true,refreshTimer,catchups=new Map()
const routes={workflows:'workflow.list',cost:'usage.cost'}
function setConnection(ok,text,isStale=false){stale=isStale;$('#connection').className=ok?'online':'offline';$('#connection').textContent=text}
function call(method,params={}){return new Promise((resolve,reject)=>{if(!ws||ws.readyState!==1)return reject(new Error('Gateway is disconnected'));const id=++next;const timer=setTimeout(()=>{if(pending.delete(id))reject(new Error(`${method} timed out`))},15000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({jsonrpc:'2.0',id,method,params}))})}
function gatewayConfig(){const write=$('#writes').checked;return{url:$('#url').value.trim(),token:$(write?'#operatorToken':'#observerToken').value,role:write?'operator':'observer',scopes:write?['read','stream','write','admin']:['read','stream']}}
function validURL(url){return /^wss:\/\//.test(url)||/^ws:\/\/(127(?:\.\d+){3}|\[::1\])(?::\d+)?\//.test(url)}
function connect(){intentional=true;ws?.close();intentional=false;clearTimeout(reconnectTimer);const c=gatewayConfig();if(!validURL(c.url))return setConnection(false,'Refused: remote gateways require WSS',true);setConnection(false,`Connecting as ${c.role}…`,true);const socket=new WebSocket(c.url);ws=socket;socket.onopen=async()=>{try{const hello=await call('gateway.hello',{protocol_version:1,client_id:'carina-web',role:c.role,scopes:c.scopes,token:c.token});granted=hello.scopes||[];const descriptors=await call('gateway.methods');methods=new Map((descriptors.methods||[]).map(x=>[x.method,x]));backoff=250;streams.clear();setConnection(true,`Connected · ${c.role} · ${granted.join(', ')}`);await resync()}catch(e){setConnection(false,e.message,true);socket.close()}};socket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.id!==undefined){const p=pending.get(m.id);if(p){pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)}}else if(m.method==='event')onEvent(m.params)};socket.onclose=()=>{if(ws!==socket)return;setConnection(false,'Stale · reconnecting',true);streams.clear();for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error('Gateway disconnected'))}pending.clear();if(!intentional)scheduleReconnect()};socket.onerror=()=>setConnection(false,'Connection failed',true)}
function scheduleReconnect(){clearTimeout(reconnectTimer);const delay=backoff;backoff=Math.min(backoff*2,10000);reconnectTimer=setTimeout(connect,delay)}
function scheduleResync(){if(refreshTimer)return;refreshTimer=setTimeout(()=>{refreshTimer=undefined;void resync()},150)}
function onEvent(event){if(!event||typeof event!=='object')return;if(event.session_id)scheduleCatchUp(event.session_id);if(/Task|Session|task\.completed|approval|question/i.test(event.type||''))scheduleResync()}
function scheduleCatchUp(sessionId){if(catchups.has(sessionId))return;catchups.set(sessionId,setTimeout(async()=>{catchups.delete(sessionId);try{const result=await call('session.attach',{session_id:sessionId,since:cursors.get(sessionId)||0});cursors.set(sessionId,result.cursor)}catch{}},100))}
async function resync(){snapshot=await call('agent.view');const sessions=[...snapshot.needs_input,...snapshot.working,...snapshot.completed],live=new Set(sessions.map(a=>a.session_id));for(const[sessionId,stream]of streams){if(live.has(sessionId))continue;if(stream.id&&canRemote('session.events.unsubscribe'))void call('session.events.unsubscribe',{subscription_id:stream.id}).catch(()=>{});streams.delete(sessionId);cursors.delete(sessionId)}for(const a of sessions){if(streams.has(a.session_id))continue;try{const result=await call('session.events.stream',{session_id:a.session_id,since:cursors.get(a.session_id)||0}),cursor=result.cursor??cursors.get(a.session_id)??0;cursors.set(a.session_id,cursor);streams.set(a.session_id,{id:result.subscription_id,cursor})}catch(e){if(!/scope|remote|method/i.test(e.message))throw e}}await render()}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const rowsOf=v=>Array.isArray(v)?v:(v?.providers||[])
async function render(){const out=$('#content');out.innerHTML='<p class="muted">Loading…</p>';try{if(tab==='agents'){if(!snapshot)snapshot=await call('agent.view');const sections=[['Needs input',snapshot.needs_input,'needs'],['Working',snapshot.working,''],['Completed',snapshot.completed,'']];out.innerHTML=sections.map(([name,rows,klass])=>`<h2>${name} <small>${rows.length}</small></h2>${rows.length?rows.map(x=>agentRow(x,klass)).join(''):'<p class="muted">None</p>'}`).join('');return}const rows=rowsOf(await call(routes[tab]));out.innerHTML=rows.length?rows.map(x=>`<div class="row"><strong>${esc(x.workflow||x.provider||x.id)}</strong><span>${esc(x.status||x.model||'')}</span><span>${esc(x.cost_usd!=null?'$'+Number(x.cost_usd).toFixed(4):x.progress!=null?Math.round(x.progress*100)+'%':'')}</span><span></span></div>`).join(''):'<p class="muted">No records.</p>'}catch(e){out.innerHTML=`<p class="error">${esc(e.message)}. Showing no authoritative snapshot; check daemon, token expiry, role, and scopes.</p>`}}
function agentRow(x,klass){return`<div class="row ${klass} ${stale?'stale':''}"><strong>${esc(x.title||x.summary||x.session_id)}</strong><span>${esc(stale?'Stale':x.state)}</span><span>${esc(x.workspace_root||x.summary||'')}</span><button data-inspect="${esc(x.session_id)}">Inspect</button></div>`}
function actionFrom(events){let decision,question,diffs=[];for(const e of events){const p=e.payload||{};if(typeof p.diff==='string')diffs.push(p.diff);const d=e.permission_decision_id||p.decision_id;if(d&&(String(e.type).match(/approval|permission/i)||p.status==='approval_requested'))decision=d;if(p.status==='approval_resolved')decision=undefined;if(p.question_id)question={id:p.question_id,prompt:p.prompt||p.question||'Question',options:Array.isArray(p.options)?p.options:[]};if(p.status==='user_question_resolved')question=undefined}return{decision,question,diffs}}
function canRemote(method){const d=methods.get(method);return Boolean(d?.remote&&granted.includes(d.scope))}
async function inspect(sessionId){const attached=await call('session.attach',{session_id:sessionId,since:0});const events=attached.events||[],a=actionFrom(events),write=$('#writes').checked;let actions='';if(a.decision)actions+=canRemote('task.approval.resolve')&&write?`<button data-approve="${esc(a.decision)}">Resolve approval</button>`:'<span class="muted">Approval pending · resolve in a local client (remote RPC unavailable)</span>';if(a.question)actions+=canRemote('task.user.answer')&&write?`<button data-answer="${esc(a.question.id)}" data-prompt="${esc(a.question.prompt)}">Answer</button>`:'<span class="muted">Question pending · answer in a local client (remote RPC unavailable)</span>';$('#content').innerHTML=`<button id="back">Back</button><h2>Session ${esc(sessionId)}</h2>${actions}<h3>Patch preview</h3><pre>${esc(a.diffs.join('\n')||'No diff in session events.')}</pre><h3>Recent activity</h3>${events.slice(-50).reverse().map(e=>`<div class="event"><strong>${esc(e.type||'event')}</strong><span>${esc(e.timestamp||'')}</span><pre>${esc(JSON.stringify(e.payload||{},null,2))}</pre></div>`).join('')}`;$('#back').onclick=render}
async function confirmed(method,params){if(!$('#writes').checked)throw new Error('Operator mode is disabled');if(!canRemote(method))throw new Error(`${method} is not exposed for remote Gateway writes`);$('#operation').textContent=JSON.stringify({method,params},null,2);$('#confirm').showModal();if(await new Promise(r=>{const d=$('#confirm');d.addEventListener('close',()=>r(d.returnValue==='default'),{once:true})}))return call(method,params)}
$('#settings').onclick=()=>$('#connect').showModal();$('#connectNow').onclick=connect;$('#refresh').onclick=()=>resync();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');b.classList.add('active');tab=b.dataset.tab;render()});$('#content').onclick=async e=>{const d=e.target.dataset||{};try{if(d.inspect)await inspect(d.inspect);if(d.approve)await confirmed('task.approval.resolve',{decision_id:d.approve,allow:true,scope:'once',approver:'web'});if(d.answer){const value=prompt(d.prompt);if(value!==null)await confirmed('task.user.answer',{question_id:d.answer,value})}}catch(err){alert(err.message)}};$('#writes').onchange=()=>{$('#modeHelp').textContent=$('#writes').checked?'Operator token · server scopes still authoritative':'Read-only observer';connect()};$('#connect').showModal()
export{esc,validURL}
