import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const webDir = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(webDir, '../..')
const html = fs.readFileSync(new URL('src-app/index.html', import.meta.url), 'utf8')
const css = fs.readFileSync(new URL('src-app/styles.css', import.meta.url), 'utf8')
const designSystemCss = fs.readFileSync(new URL('src-app/design-system/styles.css', import.meta.url), 'utf8')
const reactApp = fs.readFileSync(new URL('src-app/App.tsx', import.meta.url), 'utf8')
const reactTrajectory = fs.readFileSync(new URL('src-app/lib/trajectory.ts', import.meta.url), 'utf8')
const reactPatterns = fs.readFileSync(new URL('src-app/patterns/index.ts', import.meta.url), 'utf8')
const trajectoryPattern = fs.readFileSync(new URL('src-app/patterns/trajectory.tsx', import.meta.url), 'utf8')
const composerPattern = fs.readFileSync(new URL('src-app/patterns/composer.tsx', import.meta.url), 'utf8')
const settingsPattern = fs.readFileSync(new URL('src-app/patterns/settings-dialog.tsx', import.meta.url), 'utf8')
const harnessPreferences = fs.readFileSync(new URL('src-app/lib/harness-preferences.ts', import.meta.url), 'utf8')
const chatStartPattern = fs.readFileSync(new URL('src-app/patterns/chat-start.tsx', import.meta.url), 'utf8')
const conversationTabsPattern = fs.readFileSync(new URL('src-app/patterns/conversation-tabs.tsx', import.meta.url), 'utf8')
const filesPanelPattern = fs.readFileSync(new URL('src-app/patterns/files-panel.tsx', import.meta.url), 'utf8')
const terminalPanelPattern = fs.readFileSync(new URL('src-app/patterns/terminal-panel.tsx', import.meta.url), 'utf8')
const carinaTheme = fs.readFileSync(new URL('../../docs/brand/design-system/carina.ts', import.meta.url), 'utf8')
const viteConfig = fs.readFileSync(new URL('vite.config.ts', import.meta.url), 'utf8')
const webPackage = JSON.parse(fs.readFileSync(new URL('package.json', import.meta.url), 'utf8'))
const tsconfig = JSON.parse(fs.readFileSync(new URL('tsconfig.json', import.meta.url), 'utf8'))
const shadcnConfig = JSON.parse(fs.readFileSync(new URL('components.json', import.meta.url), 'utf8'))
const tauriConfig = JSON.parse(fs.readFileSync(path.join(root, 'integrations/tauri/src-tauri/tauri.conf.json'), 'utf8'))
const assetFiles = [
  'assets/brand-variables.css',
  'assets/logo/carina-symbol.svg',
  'assets/logo/carina-symbol-high-contrast.svg',
  'assets/logo/carina-horizontal-brand.svg',
  'assets/logo/carina-horizontal-monochrome.svg',
  'assets/logo/carina-sprite.svg',
  'assets/fonts/geist-sans-latin-variable.woff2',
  'assets/fonts/geist-mono-latin-variable.woff2',
]

assert.match(html, /Carina Harness/)
for (const file of assetFiles) assert.ok(fs.existsSync(path.join(webDir, file)), `missing ${file}; run the asset sync step`)
assert.ok(fs.existsSync(path.join(root, 'integrations/tauri/src-tauri/icons/icon.png')), 'missing Tauri icon; run the asset sync step')

assert.match(css, /--color-accent/)
assert.match(css, /border:\s*1px dashed/)
assert.match(css, /resize:\s*none/)
assert.match(css, /prefers-reduced-motion/)
assert.match(css, /var\(--font-family-mono\)/)
assert.match(css, /\.react-composer \.ui-textarea:focus-visible\s*\{\s*outline:\s*0;/)
const composerFocusRule = css.match(/\.react-composer:focus-within\s*\{([^}]*)\}/)?.[1] ?? ''
assert.doesNotMatch(composerFocusRule, /outline\s*:/, 'composer focus must not add a nested outline')
assert.match(designSystemCss, /\.ui-checkbox[\s\S]*appearance:\s*none/)
assert.match(designSystemCss, /\.ui-checkbox:checked/)
assert.match(designSystemCss, /\.ui-switch[\s\S]*appearance:\s*none/)
assert.match(designSystemCss, /\.ui-switch:checked/)

assert.match(reactApp, /TrajectoryView/)
assert.match(reactApp, /<Surface /)
assert.doesNotMatch(reactApp, /function ReactSurface/, 'route surface composition belongs to the patterns layer')
assert.match(reactApp, /session\.items/)
assert.match(reactApp, /TrajectoryStreamController/)
assert.match(reactApp, /harness\.submit/)
assert.doesNotMatch(reactApp, /call\(['"](?:session\.create|artifact\.upload|execution\.start)['"]/, 'remote Harness writes must use the bounded composition RPC')
assert.match(reactApp, /loadHarnessPreferences/)
assert.match(reactApp, /saveHarnessPreferences/)
assert.match(reactApp, /loadGatewaySessionToken/)
assert.match(reactApp, /saveGatewaySessionToken\(token\)/)
assert.match(reactApp, /if \(!autoConnect \|\| autoConnectStarted\.current\) return/)
assert.match(reactApp, /const timer = window\.setTimeout\(\(\) => \{/)
assert.match(reactApp, /autoConnectStarted\.current = true\s+connect\(true\)/)
assert.match(reactApp, /mobilePanelOpen/)
assert.match(reactApp, /SessionList/)
assert.match(reactApp, /useState\(false\)/)
assert.match(reactApp, /setPanelCollapsed\(Boolean\(session\)\)/)
assert.match(reactApp, /startNewSession/)
assert.match(css, /\.react-harness\.empty-shell \{ grid-template-columns: 0px var\(--layout-empty-sidebar-width\) minmax\(0, 1fr\);/)
assert.match(css, /\.empty-shell\.panel-collapsed:not\(\.mobile-panel-open\) \{ grid-template-columns: var\(--layout-rail-width\) 0px minmax\(0, 1fr\);/)
assert.match(css, /\.empty-shell\.panel-collapsed:not\(\.mobile-panel-open\) \.react-workspace \{[^}]*opacity: 0;/)
assert.match(reactApp, /label="Open sidebar"/)
assert.match(css, /@keyframes react-surface-in/)
assert.match(designSystemCss, /@keyframes ui-dialog-content-in/)
assert.match(chatStartPattern, /Switch to Operator to run/)
assert.match(chatStartPattern, /Full power, with a return path\./)
assert.doesNotMatch(chatStartPattern, /Into the Unknown/)
assert.match(reactPatterns, /Composer/)
assert.match(reactPatterns, /SettingsDialog/)
assert.match(reactPatterns, /TrajectoryView/)
assert.match(trajectoryPattern, /EVENT INSPECTOR/)
assert.match(trajectoryPattern, /data-trajectory/)
assert.match(composerPattern, /Attach images/)
assert.match(composerPattern, /blockedReason\.startsWith\('Switch to Operator'\)/)
assert.match(composerPattern, /disabled=\{!canRun\}/)
assert.match(composerPattern, /react-run-state/)
assert.match(settingsPattern, /aria-busy=\{connecting\}/)
assert.match(settingsPattern, /Connect on launch/)
assert.match(settingsPattern, /Token storage is limited to this browser tab/)
assert.match(settingsPattern, /<Switch /)
assert.match(harnessPreferences, /loadHarnessPreferences\([^\n]*browserStorage\('localStorage'\)/)
assert.match(harnessPreferences, /loadGatewaySessionToken\([^\n]*browserStorage\('sessionStorage'\)/)
assert.match(harnessPreferences, /saveGatewaySessionToken\([^\n]*browserStorage\('sessionStorage'\)/)
assert.match(conversationTabsPattern, /Trajectory/)
assert.match(filesPanelPattern, /aria-label=\{open \? 'Files'/)
assert.match(reactApp, /harness\.workspace\.tree/)
assert.match(terminalPanelPattern, /aria-label="Terminal"/)
assert.match(reactTrajectory, /deriveTrajectoryRows/)
assert.match(reactTrajectory, /duration_ms/)
assert.doesNotMatch(carinaTheme, /@astryxdesign\//, 'theme adapter must not depend on an uninstalled runtime package')
assert.match(carinaTheme, /export interface CarinaTheme/)
assert.match(carinaTheme, /satisfies CarinaTheme/)
assert.match(carinaTheme, /carinaThemeModes/)
assert.match(viteConfig, /root: 'src-app'/)
assert.match(viteConfig, /outDir: '..\/dist'/)
assert.match(viteConfig, /__CARINA_VERSION__/)
assert.match(reactApp, /client_version: __CARINA_VERSION__/)
assert.match(viteConfig, /command === 'build' \|\| isPreview \? '\.\/' : '\/integrations\/web\/'/)
assert.match(html, /main\.tsx/)
assert.equal(fs.existsSync(path.join(webDir, 'src-app/main.tsx')), true)
assert.equal(fs.existsSync(path.join(webDir, 'src-app/main.jsx')), false)
assert.equal(fs.existsSync(path.join(webDir, 'src-app/App.jsx')), false)
assert.equal(fs.existsSync(path.join(webDir, 'src-app/patterns/connection-dialog.tsx')), false)
assert.equal(fs.existsSync(path.join(webDir, 'src-app/components/ui/separator.tsx')), false)
assert.equal(tsconfig.compilerOptions.strict, true)
assert.equal(shadcnConfig.tsx, true)
assert.equal(webPackage.dependencies.react.startsWith('^19'), true)
assert.equal(webPackage.devDependencies.vite.startsWith('^8'), true)
assert.equal(webPackage.devDependencies['@vitejs/plugin-react'] !== undefined, true)
assert.equal(webPackage.devDependencies.typescript !== undefined, true)
assert.equal(webPackage.scripts.typecheck, 'tsc --noEmit')
assert.equal(webPackage.dependencies['class-variance-authority'], undefined)

assert.equal(tauriConfig.productName, 'Carina Harness')
assert.equal(tauriConfig.build.frontendDist, '../../web/dist')
assert.equal(tauriConfig.app.windows[0].minWidth, 860)

for (const legacy of ['index.html', 'app.js', 'app.css']) {
  assert.equal(fs.existsSync(path.join(webDir, legacy)), false, `legacy web file remains: ${legacy}`)
}

console.log('web and Tauri Harness surface smoke: ok')
