import * as vscode from 'vscode'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { RpcClient } from './rpc'

type Agent = { session_id:string;task_id?:string;state:string;title?:string;summary?:string;workspace_root?:string;updated_at?:string;bucket?:Bucket }
type Bucket='needs_input'|'working'|'completed'
type View={needs_input:Agent[];working:Agent[];completed:Agent[]}
type Event={type?:string;timestamp?:string;payload?:Record<string,unknown>;permission_decision_id?:string}
class AgentItem extends vscode.TreeItem {
  constructor(readonly agent:Agent,stale:boolean){super(agent.title||agent.summary||agent.session_id,vscode.TreeItemCollapsibleState.None);const bucket=agent.bucket||'working';this.description=`${stale?'Stale · ':''}${bucket==='needs_input'?'Needs input':bucket==='completed'?'Completed':'Working'} · ${agent.state}`;this.tooltip=[agent.summary,agent.workspace_root,agent.session_id].filter(Boolean).join('\n');this.contextValue=`carinaAgent.${bucket}`;this.iconPath=new vscode.ThemeIcon(bucket==='needs_input'?'bell-dot':bucket==='completed'?'pass':'sync~spin');this.command={command:'carina.inspect',title:'Inspect',arguments:[agent]}}
}
class Agents implements vscode.TreeDataProvider<AgentItem>,vscode.Disposable{
  private changed=new vscode.EventEmitter<void>();readonly onDidChangeTreeData=this.changed.event;private view:View={needs_input:[],working:[],completed:[]};private stale=true;private streams=new Map<string,{id?:string;cursor:number}>();private cursors=new Map<string,number>();private refreshTimer?:NodeJS.Timeout;private catchups=new Map<string,NodeJS.Timeout>();private disposers:Array<()=>void>=[]
  constructor(readonly rpc:RpcClient,readonly status:vscode.StatusBarItem){this.disposers.push(rpc.onNotification((method,params)=>this.onNotification(method,params)),rpc.onState((state,error)=>{this.stale=state!=='connected';if(this.stale)this.streams.clear();this.status.text=state==='connected'?'$(hubot) Carina':state==='connecting'?'$(sync~spin) Carina connecting':'$(debug-disconnect) Carina stale';this.status.tooltip=error?.message||state;if(state==='connected')void this.snapshot();this.changed.fire()}))}
  dispose():void{if(this.refreshTimer)clearTimeout(this.refreshTimer);this.catchups.forEach(clearTimeout);this.changed.dispose();this.disposers.forEach(d=>d())}
  refresh():void{void this.snapshot()}
  getTreeItem(i:AgentItem):vscode.TreeItem{return i}
  getChildren():AgentItem[]{return(['needs_input','working','completed']as Bucket[]).flatMap(bucket=>this.view[bucket].map(a=>new AgentItem({...a,bucket},this.stale)))}
  private queueRefresh():void{if(this.refreshTimer)return;this.refreshTimer=setTimeout(()=>{this.refreshTimer=undefined;void this.snapshot()},150)}
  private onNotification(method:string,params:unknown):void{if(method!=='event'||typeof params!=='object'||!params)return;const event=params as Event&{session_id?:string};if(event.session_id)this.queueCatchUp(event.session_id);if(/Task|Session|task\.completed|approval|question/i.test(event.type||''))this.queueRefresh()}
  private queueCatchUp(sessionID:string):void{if(this.catchups.has(sessionID))return;this.catchups.set(sessionID,setTimeout(()=>{this.catchups.delete(sessionID);void this.catchUp(sessionID)},100))}
  private async catchUp(sessionID:string):Promise<void>{try{const result=await this.rpc.call<{cursor:number}>('session.attach',{session_id:sessionID,since:this.cursors.get(sessionID)||0});this.cursors.set(sessionID,result.cursor)}catch{/* connection state drives the visible stale marker */}}
  private async snapshot():Promise<void>{try{this.view=await this.rpc.call<View>('agent.view');this.stale=false;const all=[...this.view.needs_input,...this.view.working,...this.view.completed],live=new Set(all.map(a=>a.session_id));for(const[sessionID,stream]of this.streams){if(live.has(sessionID))continue;if(stream.id)void this.rpc.call('session.events.unsubscribe',{subscription_id:stream.id}).catch(()=>{});this.streams.delete(sessionID);this.cursors.delete(sessionID)}this.status.text=`$(hubot) Carina ${all.length} · ${this.view.needs_input.length} need input`;this.status.tooltip='Live snapshot from carina-daemon';this.changed.fire();for(const a of all){if(this.streams.has(a.session_id))continue;const stream=await this.rpc.call<{subscription_id?:string;cursor?:number}>('session.events.stream',{session_id:a.session_id,since:this.cursors.get(a.session_id)||0});const cursor=stream.cursor??this.cursors.get(a.session_id)??0;this.cursors.set(a.session_id,cursor);this.streams.set(a.session_id,{id:stream.subscription_id,cursor})}}catch(e){this.stale=true;this.status.text='$(debug-disconnect) Carina stale';this.status.tooltip=e instanceof Error?e.message:String(e);this.changed.fire()}}
}
async function events(rpc:RpcClient,a:Agent):Promise<Event[]>{const x=await rpc.call<{events?:Event[]}>('session.attach',{session_id:a.session_id,since:0});return x.events||[]}
function pendingAction(es:Event[]):{decision?:string;question?:{id:string;prompt:string;options:string[]}}{let decision:string|undefined;let question:any;for(const e of es){const p=e.payload||{};const d=String(e.permission_decision_id||p.decision_id||'');if(d&&(/approval|permission/i.test(e.type||'')||p.status==='approval_requested'))decision=d;const q=String(p.question_id||'');if(q)question={id:q,prompt:String(p.prompt||p.question||'Question'),options:Array.isArray(p.options)?p.options.map(String):[]};if(p.status==='approval_resolved')decision=undefined;if(p.status==='user_question_resolved')question=undefined}return{decision,question}}
function transcript(es:Event[]):string{return es.map(e=>{const p=e.payload||{};const text=p.message||p.summary||p.output||p.prompt||p.status||'';return `### ${e.type||'event'}\n${e.timestamp||''}\n\n${typeof text==='string'?text:'\u0060\u0060\u0060json\n'+JSON.stringify(text,null,2)+'\n\u0060\u0060\u0060'}`}).join('\n\n')||'No events recorded.'}
export function activate(ctx:vscode.ExtensionContext):void{
  const configured=vscode.workspace.getConfiguration('carina').get<string>('socketPath')||'';const rpc=new RpcClient(configured||join(homedir(),'.carina','daemon.sock'));const status=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);status.show();const agents=new Agents(rpc,status);ctx.subscriptions.push(rpc,status,agents,vscode.window.registerTreeDataProvider('carina.agents',agents));const command=(name:string,fn:(...a:any[])=>unknown)=>ctx.subscriptions.push(vscode.commands.registerCommand(name,fn))
  command('carina.refresh',()=>agents.refresh())
  command('carina.inspect',async(a:Agent)=>{const doc=await vscode.workspace.openTextDocument({language:'markdown',content:`# ${a.title||a.session_id}\n\n${a.summary||''}\n\n${transcript(await events(rpc,a))}`});await vscode.window.showTextDocument(doc)})
  command('carina.attach',async(a:Agent)=>vscode.commands.executeCommand('carina.inspect',a))
  command('carina.steer',async(a:Agent)=>{if(!a.task_id)return vscode.window.showWarningMessage('This agent has no active task.');const message=await vscode.window.showInputBox({prompt:`Steer ${a.title||a.task_id}`,ignoreFocusOut:true});if(message)await rpc.call('task.steer',{task_id:a.task_id,message})})
  command('carina.approve',async(a:Agent)=>{const action=pendingAction(await events(rpc,a));if(!action.decision)return vscode.window.showInformationMessage('No pending approval was found in this session.');const pick=await vscode.window.showWarningMessage(`Resolve approval ${action.decision}?`,{modal:true,detail:a.summary},'Allow once','Deny');if(pick)await rpc.call('task.approval.resolve',{decision_id:action.decision,allow:pick==='Allow once',scope:'once',approver:'vscode'})})
  command('carina.answer',async(a:Agent)=>{const action=pendingAction(await events(rpc,a));if(!action.question)return vscode.window.showInformationMessage('No pending question was found in this session.');const value=action.question.options.length?await vscode.window.showQuickPick(action.question.options,{placeHolder:action.question.prompt,ignoreFocusOut:true}):await vscode.window.showInputBox({prompt:action.question.prompt,ignoreFocusOut:true});if(value!==undefined)await rpc.call('task.user.answer',{question_id:action.question.id,value})})
  command('carina.previewPatch',async(a:Agent)=>{const es=await events(rpc,a);const diffs=es.flatMap(e=>{const p=e.payload||{};return typeof p.diff==='string'?[p.diff]:[]});const doc=await vscode.workspace.openTextDocument({language:'diff',content:diffs.join('\n')||'No patch diff is available in the session event stream.'});await vscode.window.showTextDocument(doc,{preview:true})})
  void rpc.connect().catch(()=>{})
}
