#!/usr/bin/env python3
"""Regenerate or verify go/microcopy/zhhant_table_gen.go from Simplified Chinese.

Requires: pip install zhconv  (OpenCC-compatible conversion)

  python3 scripts/gen_zh_hant.py          # rewrite generated table
  python3 scripts/gen_zh_hant.py --check  # exit 1 if table is stale

Source of truth remains the zh catalogs (JSON pools + TUI catalog ZH fields).
Traditional Chinese (zh-Hant) is derived, not independently authored.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import zhconv
except ImportError:
    print("error: install zhconv (pip install zhconv)", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "go/microcopy/zhhant_table_gen.go"


def collect_zh_strings() -> set[str]:
    zh_strings: set[str] = set()

    for path in (ROOT / "go/microcopy/pools").glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))

        def walk(o):
            if isinstance(o, dict):
                for k, v in o.items():
                    if k == "zh":
                        if isinstance(v, str) and v.strip():
                            zh_strings.add(v)
                        elif isinstance(v, list):
                            for line in v:
                                if isinstance(line, str) and line.strip():
                                    zh_strings.add(line)
                        elif isinstance(v, dict):
                            for lines in v.values():
                                if isinstance(lines, list):
                                    for line in lines:
                                        if isinstance(line, str) and line.strip():
                                            zh_strings.add(line)
                    else:
                        walk(v)
            elif isinstance(o, list):
                for item in o:
                    walk(item)

        walk(data)

    for path in (ROOT / "go/tui").glob("i18n_catalog*.go"):
        text = path.read_text(encoding="utf-8")
        i = 0
        while True:
            j = text.find("catalog(", i)
            if j < 0:
                break
            k = j + len("catalog(")
            while k < len(text) and text[k] in " \t\n":
                k += 1
            if text.startswith("Msg", k):
                while k < len(text) and (text[k].isalnum() or text[k] == "_"):
                    k += 1
            elif k < len(text) and text[k] == '"':
                k += 1
                while k < len(text) and text[k] != '"':
                    k += 2 if text[k] == "\\" else 1
                k += 1
            strings: list[str] = []
            while len(strings) < 6 and k < len(text):
                while k < len(text) and text[k] in " \t\n,":
                    k += 1
                if k >= len(text) or text[k] != '"':
                    break
                k += 1
                buf: list[str] = []
                while k < len(text):
                    c = text[k]
                    if c == "\\":
                        buf.append(text[k : k + 2])
                        k += 2
                        continue
                    if c == '"':
                        k += 1
                        break
                    buf.append(c)
                    k += 1
                raw = "".join(buf)
                s = (
                    raw.replace("\\n", "\n")
                    .replace("\\t", "\t")
                    .replace('\\"', '"')
                    .replace("\\\\", "\\")
                )
                strings.append(s)
            if len(strings) >= 2 and strings[1].strip():
                zh_strings.add(strings[1])
            i = k

    plural = (ROOT / "go/microcopy/plural.go").read_text(encoding="utf-8")
    for m in re.finditer(r'"zh":\s*\{[^}]*other:\s*"((?:\\.|[^"\\])*)"', plural):
        zh_strings.add(m.group(1).replace('\\"', '"').replace("\\n", "\n"))

    for path in (ROOT / "go/tui").glob("i18n.go"):
        for m in re.finditer(
            r'LocaleChinese:\s*"((?:\\.|[^"\\])*)"', path.read_text(encoding="utf-8")
        ):
            zh_strings.add(m.group(1))

    return zh_strings


def render_table(zh_strings: set[str]) -> str:
    mapping = {s: zhconv.convert(s, "zh-hant") for s in zh_strings}
    chars: set[str] = set()
    for s in zh_strings:
        chars.update(s)
    char_map = {
        ch: zhconv.convert(ch, "zh-hant")
        for ch in chars
        if zhconv.convert(ch, "zh-hant") != ch
    }

    lines = [
        "// Code generated by scripts/gen_zh_hant.py; DO NOT EDIT.",
        "",
        "package microcopy",
        "",
        "// s2tExact maps authored Simplified Chinese strings to Traditional Chinese.",
        "// Generated with zhconv (OpenCC-compatible). Source of truth remains zh.",
        "var s2tExact = map[string]string{",
    ]
    for s in sorted(mapping, key=lambda x: (-len(x), x)):
        t = mapping[s]
        if s == t:
            continue
        lines.append(
            "\t%s: %s,"
            % (json.dumps(s, ensure_ascii=False), json.dumps(t, ensure_ascii=False))
        )
    lines += [
        "}",
        "",
        "// s2tChar converts individual runes that differ in Traditional.",
        "var s2tChar = map[rune]rune{",
    ]
    for ch in sorted(char_map, key=lambda c: ord(c)):
        lines.append(
            "\t%d: %d, // %s -> %s" % (ord(ch), ord(char_map[ch]), ch, char_map[ch])
        )
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if go/microcopy/zhhant_table_gen.go is out of date",
    )
    args = parser.parse_args()

    zh_strings = collect_zh_strings()
    body = render_table(zh_strings)
    phrase_n = sum(
        1 for s in zh_strings if zhconv.convert(s, "zh-hant") != s
    )

    if args.check:
        if not OUT.is_file():
            print(f"error: missing {OUT.relative_to(ROOT)}; run scripts/gen_zh_hant.py", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != body:
            print(
                "error: go/microcopy/zhhant_table_gen.go is stale\n"
                "  Simplified Chinese catalogs changed without regenerating Traditional tables.\n"
                "  Fix: python3 scripts/gen_zh_hant.py && git add go/microcopy/zhhant_table_gen.go",
                file=sys.stderr,
            )
            return 1
        print(
            "zh-Hant table up to date (%d unique zh, %d converted phrases)"
            % (len(zh_strings), phrase_n)
        )
        return 0

    OUT.write_text(body, encoding="utf-8")
    print(
        "wrote %s (%d phrases, %d unique zh)"
        % (OUT.relative_to(ROOT), phrase_n, len(zh_strings))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
