import './styles.css'

// Icon suppliers are intentionally re-exported here so feature code depends on
// the project boundary instead of importing the icon package directly.
export {
  Activity,
  ArrowUp,
  ChevronDown,
  CircleDot,
  Download,
  File,
  FileImage,
  Folder,
  FolderOpen,
  Inbox,
  LayoutPanelLeft,
  ListChecks,
  Menu,
  Monitor,
  Moon,
  PanelBottomClose,
  PanelBottomOpen,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Plug,
  Plus,
  RefreshCw,
  Settings2,
  ShieldCheck,
  Search,
  Sparkles,
  Sun,
  Terminal,
  X,
} from 'lucide-react'
export type { LucideIcon } from 'lucide-react'

export {
  Badge,
  Button,
  Checkbox,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  Icon,
  IconButton,
  Input,
  Label,
  ScrollArea,
  Switch,
  Textarea,
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
  cn,
} from './primitives'

export type {
  BadgeProps,
  BadgeTone,
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  CheckboxProps,
  DialogContentProps,
  DialogProps,
  IconButtonProps,
  IconProps,
  InputProps,
  LabelProps,
  SwitchProps,
  TextareaProps,
} from './primitives'
